name: ios build scripts

on:
  push:
    branches:
      - development
      - main
    paths:
      - '.github/workflows/ios-build-scripts.yml'
      - 'apple/**'
      - '!apple/README.md'
      - 'scripts/**'
      - 'tools/**'
      - 'apple.sh'
      - 'ios.sh'
  pull_request:
    branches:
      - development
      - main
    paths:
      - '.github/workflows/ios-build-scripts.yml'
      - 'apple/**'
      - '!apple/README.md'
      - 'scripts/**'
      - 'tools/**'
      - 'apple.sh'
      - 'ios.sh'

jobs:
  build-main-on-macos-sonoma:
    name: ios main on sonoma
    runs-on: macos-14
    strategy:
      matrix:
        xcode: [ '15.3' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '5a3224b35730a19c92b4e0039b1937d23cdd64af'
      - name: prerequisites
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm meson
      - name: set up xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
      - name: run the build script
        run: ./ios.sh -x --disable-armv7 --disable-armv7s --disable-x86-64 --disable-i386 --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
      # - name: print build logs
      #   run: zip ./prebuilt -o prebuilt.zip
      - name: create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-v4.5
          path: |
            ./prebuilt
  # build-main-on-macos-ventura:
  #   name: ios main on ventura
  #   runs-on: macos-13
  #   strategy:
  #     matrix:
  #       xcode: [ '14.3.1', '15.2' ]
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: prerequisites
  #       run: brew install autoconf automake libtool pkg-config curl git cmake nasm
  #     - name: set up xcode
  #       run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
  #     - name: run the build script
  #       run: ./ios.sh --xcframework --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib
  #     - name: print build logs
  #       if: ${{ always() }}
  #       run: cat build.log
  #     - name: print ffbuild logs
  #       if: ${{ failure() }}
  #       run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
  # build-lts-on-macos-monterey:
  #   name: ios lts on monterey
  #   runs-on: macos-12
  #   strategy:
  #     matrix:
  #       xcode: [ '13.4.1', '14.2' ]
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: prerequisites
  #       run: brew install autoconf automake libtool pkg-config curl git cmake nasm
  #     - name: set up xcode
  #       run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
  #     - name: run the build script
  #       run: ./ios.sh --lts --enable-ios-audiotoolbox --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-zlib
  #     - name: print build logs
  #       if: ${{ always() }}
  #       run: cat build.log
  #     - name: print ffbuild logs
  #       if: ${{ failure() }}
  #       run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
